[project]
name = "el-bot"
version = "0.1.0"
description = "Telegram bot EL mentors"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.24.0",
    "apscheduler>=3.11.2",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]
